### DISCUSSION TITLE
Xfce | Wildlife

### DISCUSSION THREAD

**Discussion by giscus** [games-on-whales/gow#220] [Q&A]
# Xfce | Wildlife

  Desktop (XFCE)
  #

  
    
      
      
      
    
    Moonlight | Wolf
  
  
    
  

A lightweight desktop environment for Unix-like operating systems.
It aims to be fast and low on system resources while being visually appealing and user-friendly.

  Installing applications
  #

In this configuration, XFCE is set up to use Flatpak in user mode.
Flatpak is a software utility for software
deployment, package management, and application virtualization for Linux. By using Flatpak in user mode, users can
install and manage applications from the Flatpak store without needing administrative privileges or modifying the base
Docker image.
This setup enhances flexibility and security, as users can add or remove applications independently of the
underlying system.

https://games-on-whales.github.io/wildlife/apps/xfce/

**Comment by Kitty-Calia** [comment]
Getting an error while trying to install org.freedesktop.Platform.openh264: Warning while trying to apple extra data: apply_extra script failed exit status 256

**Reply by ABeltramo** [reply]
Which specific action were you performing?

**Reply by Kitty-Calia** [reply]
Just installing Flatseal at first, then I tried any other app and it's the same thing. It's a necessary runtime for most of them.

Edit: Just to add I used the exact config on Wildlife just adding my mounts for shared folders. Also I'm running on a Fedora Server with and AMD graphics card with this docker-compose file:

```yaml
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/home/kittycalia/containers/wolf
    volumes:
      - /home/kittycalia/containers/wolf:/home/kittycalia/containers/wolf:rw
      - /home/kittycalia/containers/wolf:/etc/wolf:rw
      - /home/kittycalia/containers/wolf/cfg:/home/kittycalia/containers/wolf/cfg:rw
      - /mnt/storage0:/mnt/storage0:rw
      - /mnt/storage1:/mnt/storage1:rw
      - /mnt/storage2:/mnt/storage2:rw
      - /tmp:/tmp:rw
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev:/dev:rw
      - /run/udev:/run/udev:rw
      - /run/user/1000:/run/user/1000:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
      - /dev/uhid:/dev/uhid
    network_mode: host
    restart: unless-stopped
```

**Reply by ABeltramo** [reply]
I can't reproduce it
![screenshot](https://github.com/user-attachments/assets/3014baed-8040-4a30-acbf-1f231846a1ee)
Although I just noticed that the default `config.toml` is missing some required options. Can you try again with the following config?
```toml
[[apps]]
title = 'Desktop (xfde)'

[apps.runner]
type = 'docker'
name = 'WolfPrism'
image = 'ghcr.io/games-on-whales/xfce:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
```

**Reply by Kitty-Calia** [reply]
It installed the library correctly now but it seems to be hanging on this during installation

![Screenshot_20250228_140307](https://github.com/user-attachments/assets/bb499590-ef7d-40d7-b9a4-84d0cf9118cc)


And it doesn't launch when it finally installs.


Edit: wow it did launch finally it took like a solid 5 minutes from pressing the icon to app launch

**Reply by Kitty-Calia** [reply]
Update: Managed to install XIVLauncher to run Final Fantasy XIV and it is working and runs smooth :) 

Just takes a long time to launch any Flatpak app, there is a huge lag between launching the app and it actually showing on screen but after that everything is normal

**Reply by ABeltramo** [reply]
I'm glad you've managed to install and run a game. I can't reproduce the slowness, could it be tied to your storage?

**Reply by Kitty-Calia** [reply]
It's running from an SSD, one of the mapped mounts is a HDD tough. I searched around and there are some people with flatpaks starting slowly maybe due to a portal taking to long to start.

Are there any needed requirements that need to be on the host other than everything mapped on the docker file?

**Reply by ABeltramo** [reply]
I'm not sure, but you could try setting the `privileged` flag to true (always in the `config.toml`).  
It'll break isolation between users, but if that fixes it for you, it means that there's some other `cap` missing..

**Reply by Kitty-Calia** [reply]
no, unfortunately it did not fix it, I have attached the log files of the install and first run, it always hangs on the 'bwrap' bits.

also I'm running it from a shared 'common' folder because I'm the only user and don't really care about isolation for now :)

[Flatseal 1st run.log](https://github.com/user-attachments/files/19037769/Flatseal.1st.run.log)
[Flatseal install.log](https://github.com/user-attachments/files/19037770/Flatseal.install.log)

**Reply by Kitty-Calia** [reply]
Update:

I just added bits and pieces from the other config.toml entries and some CAPs I found that  helped other users running flatpak in Docker and it works now at full speed :) :

```toml
[[apps]]
start_virtual_compositor = true
title = 'Desktop (xfde)'

[apps.runner]
type = 'docker'
name = 'WolfXfde'
image = 'ghcr.io/games-on-whales/xfce:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = [  ]
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": true,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN", "SYS_CHROOT", "SETUID", "SETGID"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
```

**Reply by ABeltramo** [reply]
Thanks for that, I'll add it as the default!

**Comment by Ataky-0** [comment]
Any tips for running Sober? An application that uses SDL to run the Roblox APK on Linux with native gameplay? I've been trying to start it, but it won't get past the SDL part (Where it says $HOME it is actually the path to my home folder, not the variable):

Goal (Host Output):
```
F: Opening user flatpak installation at path $HOME/.local/share/flatpak
F: Opening user flatpak installation at path $HOME/.local/share/flatpak
F: Skipping parental controls check for app/org.vinegarhq.Sober/x86_64/master since parental controls are disabled globally
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path $HOME/.local/share/flatpak
F: $HOME/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/47/7afb1978e8bdc0aab3209d16a0f2e89aed1303e0c9496a44de7944ebf331b726/files/lib32 does not exist
F: Cleaning up unused container id 1263579913
F: Cleaning up per-app-ID state for org.vinegarhq.Sober
F: Allocated instance id 2696001360
F: Add defaults in dir /org/vinegarhq/Sober/
F: Add locks in dir /org/vinegarhq/Sober/
F: Allowing x11 access
F: Allowing pulseaudio access
F: Allowing session-dbus access
F: Allowing system-dbus access
F: Running 'bwrap --args 36 -- xdg-dbus-proxy --args=39'
F: Running 'bwrap --args 36 -- sober'
lifecycle: app_start delta=5.50002e-05ms
lifecycle: logging_started delta=1.55434ms
info: app tag = s021-1760-x86_64-gnu
lifecycle: update_flags_from_remote_manifest delta=1.44859ms
info: using remote manifest object: '{"r1":1,"u":1}'
lifecycle: fs_init delta=196.496ms
lifecycle: core_runtime delta=1.40217ms
lifecycle: app_core delta=1.79341ms
lifecycle: app_main delta=164.52ms (( THAT'S WHERE IT STOPS ))
sober rpc: connected to user arrpc#0 - *******************
lifecycle: sdl_init delta=878.822ms
info: Trying video backend preference: x11,wayland
info: Using video backend: x11
info: Trying audio subsystem: pulseaudio
info: Using audio subsystem: pulseaudio
lifecycle: global_window_init delta=251.498ms
lifecycle: interface_init delta=39.0429ms
. . .
```
Actual (WolfXfce Output):

```
F: Opening user flatpak installation at path /home/retro/.local/share/flatpak
F: Opening user flatpak installation at path /home/retro/.local/share/flatpak
F: Skipping parental controls check for app/org.vinegarhq.Sober/x86_64/master since parental controls are disabled globally
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/retro/.local/share/flatpak
F: /home/retro/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/47/e535742383fe522320d535b18c10cdbe26f4484983dbfdcabd8010c05ddba8d7/files/lib32 does not exist
F: Cleaning up unused container id 3959045173
F: Cleaning up per-app-ID state for org.vinegarhq.Sober
F: Allocated instance id 4286022970
F: Add defaults in dir /org/vinegarhq/Sober/
F: Add locks in dir /org/vinegarhq/Sober/
F: Allowing wayland access
F: Allowing pulseaudio access
F: Allowing session-dbus access
F: Allowing system-dbus access
F: Failed to run in transient scope: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Failed to set unit properties: No such process
F: Running 'bwrap --args 33 -- xdg-dbus-proxy --args=35'
F: Running 'bwrap --args 33 -- sober'
lifecycle: app_start delta=6.79996e-05ms
lifecycle: logging_started delta=0.741899ms
info: app tag = s021-1760-x86_64-gnu
lifecycle: update_flags_from_remote_manifest delta=0.828815ms
info: using remote manifest object: '{"r1":1,"u":1}'
lifecycle: fs_init delta=201.989ms
lifecycle: core_runtime delta=0.949689ms
lifecycle: app_core delta=1.24421ms
lifecycle: app_main delta=165.006ms
```

My application config is mostly the same as Kitty-Calia's except i mount 2 volumes.

My docker-compose.yml:

```
version: "3"
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - $HOME/Share/WolfXfce:/shared:rw
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
      - /run/user/1000:/run/user/1000:rw
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped
```

**Reply by ABeltramo** [reply]
Have you tried using the latest posted version?

```toml
[[apps]]
start_virtual_compositor = true
title = 'Desktop (xfde)'

[apps.runner]
type = 'docker'
name = 'WolfXfde'
image = 'ghcr.io/games-on-whales/xfce:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = [  ]
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": true,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN", "SYS_CHROOT", "SETUID", "SETGID"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
```

Could it be that you've switched the output logs? I can see you've added `(( THAT'S WHERE IT STOPS ))` but that was tagged as `Goal (Host Output)` which I'm not sure makes sense :sweat_smile:
