### ISSUE TITLE
Provide single-usage container apps

### ISSUE THREAD

**Issue by QuaiGoner** [games-on-whales/gow#100]
Hello. Hope its not too rude to post it here, but it would be much easier and cleaner for new users to just add to their docker-compose files another container like RetroArch, which contains xorg,pulse,udev,sunshine and app in following form:

```
 gow-retroarch
    image:  gow-retroarch:latest
    container_name:  gow-retroarch101
    group_add:
      - 109 #OR whatever required for video and graphics
    environment:
      - TZ=Europe/London
      - SUNSHINE_USER=admin
      - SUNSHINE_PASS=admin
      - SUNSHINE_WEB_UI=49999
      - SUNSHINE_ENCODER=vaapi
      - XORG_RESOLUTION: 1280x720
      - XORG_CURRENT_OUTPUT: HDMI-0 #OR some other virtual output
      - XORG_REFRESH_RATE: 60
      - XORG_FORCE_RESOLUTION: true
    volumes:
      - ./config/gow-retroarch101/config:/config #Root folder with subfolders like /retroarch, /sunshine...
      - /mnt/Games:/Games:ro
      - /dev/input:/dev/input:ro
      - udev:/run/udev/:ro
    devices:
      # VAAPI/GFX Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/fb0:/dev/fb0
    network_mode: host
    privileged: true
#all other ports required by sunshine
    restart: unless-stopped
```
